#install.packages('tidyverse')
#install.packages('xml2')
#install.packages('rvest')
#install.packages('stringr')
#install.packages('jsonlite')
#install.packages('httr')

#loading the package:
# library(xml2)
# library(rvest)
# library(stringr)
# library(jsonlite)
# library(tibble)
# library(dplyr)
# library(lubridate)
# library(httr)
# library(tidyverse)
# library(rlang)

# ctl00$ContentPlaceHolder1$ddlProjectName
# \"\>[a-zA-Z0-9\-\(\)\ \,\/\\\.\-\;\&\#\'\@]{1,}\<\/option\>

tif_project_names <- c("100 N. Euclid (352-136)",
  "1001 Locust (352-108)",
  "10th and Locust TIF Plan",
  "1111 Olive (352-127)",
  "1133 Washington Avenue (352-48)",
  "1136 Washington Avenue (A.D. Brown Bldg.) (352-58)",
  "1141-51 S. 7th St. (352-23)",
  "11th Street Corridor Blossom House",
  "11th Street Corridor TIF PlanProj C - Lyric  ",
  "11th Street TIF Plan",
  "11th Street, Project B (Blossom House) TIF Plan",
  "1200 Main/South Loop Project 01 (KC Live) TIF",
  "1200 Main/South Loop Project 02 (H and R Block) TIF",
  "1200 Main/South Loop Project 03a (President Hotel)",
  "1200 Main/South Loop Project 04 TIF Plan",
  "1200 Main/South Loop Project 05 TIF Plan",
  "1200 Main/South Loop Project 06 TIF Plan",
  "1200 Main/South Loop Project 07 (HRB Expansion)",
  "1200 Main/South Loop Project 08 (Sprint Arena)",
  "1200 Main/South Loop Project 09 TIF Plan",
  "1200 Main/South Loop Project 10 TIF Plan",
  "1200 Main/South Loop Project 11 TIF Plan",
  "1200 Main/South Loop Project 12 TIF Plan",
  "1200 Main/South Loop Projects 13 and 14 TIF Plan",
  "1200 MainSouth Loop TIF - Proj 3aPhase II Apts ",
  "1225 Washington (352-122)",
  "12th &amp; Wyandotte TIF Plan",
  "12th and Wyandotte (Aladdin Hotel) TIF Plan",
  "1300 Convention Plaza (352-47)",
  "1312 Washington (Garment Row Lofts 352-30)",
  "13th &amp; Washington TIF Plan",
  "1400 Washington Avenue/Sky House (352-96)",
  "1449-1601 S. Jefferson (352-132)",
  "1505 Missouri Ave. (352-21)",
  "1717 Market Place TIF Plan",
  "1900 Washington (352-107)",
  "1910 Locust (352-102)",
  "19th Terrace &amp; Central TIF Plan (Overall)",
  "19th Terrace and Central Project 2a b and c TIF Plan",
  "19th Terrace and Central TIF Plan",
  "1st Amended &amp; Restated Appleton City Downtown TIF",
  "2200 Gravois (352-85)",
  "22nd &amp; Main Projects 18 &amp; 21, Parking Lot TIF",
  "22nd &amp; Main TIFH.D. Lee Bldg - Project 12c &amp; 12r",
  "22nd &amp; Main TIFProject 16",
  "22nd and Main - Project 01 Freight House Bldg",
  "22nd and Main - Project 02 Marietta Chair Bldg",
  "22nd and Main - Project 10 1900 Main Bldg",
  "22nd and Main - Project 12 and 13 H.D. Lee",
  "22nd and Main - Project 14 Safeway Bldg",
  "22nd and Main - Project 16 Columbia and Gray Bldgs",
  "22nd and Main - Project 21 AD Jacobson Building",
  "22nd and Main - Project 22 Creamery Building",
  "22nd and Main - Project 24 Morr Transfer Bldg",
  "22nd and Main - Project 27 The Arthel Bldg",
  "22nd and Main - Project 28 Candle Building",
  "2727 Washington (352-133)",
  "2nd Amended &amp; Restated Atkinson Rd TIF Plan",
  "2nd and Douglas TIF Plan",
  "3150 South Grand (352-120)",
  "32 North Euclid (352-149)",
  "3693 Forest Park (352-115)",
  "374 South Grand (352-113)",
  "3800 Park Ave. (352-12)",
  "3949 Lindell Blvd (352-70)",
  "39th &amp; Prospect",
  "410 N. Jefferson (West Gate) Lofts (352-45)",
  "4100 Forest Park (352-86)",
  "4200 Laclede Ave. (352-19)",
  "4249 Michigan (352-129)",
  "4391-99 West Pine Condos (352-10)",
  "43rd and Main - American Century (Project 2)",
  "43rd and Main - Consolidated SAF TIF Plan",
  "43rd and Main - Office Depot (Project 1)",
  "43rd and Main - Projects 2 and 5",
  "43rd and Main - Projects 8a and 8b",
  "4494 Lindell TIF (352-148)",
  "4548 West Pine Condominiums (352-5)",
  "45th and Main TIF Plan",
  "4900 Manchester (352-112)",
  "50 Highway Tax Increment Financing Plan",
  "500 Kingshighway (352-124)",
  "5700 Arsenal (352-60)",
  "5819 Delmar Housing (352-80C)",
  "60 West-Malco",
  "60 West-RPA-2A",
  "60/61 TIF District",
  "600 Washington Ave.-St.Louis Centre (352-88)",
  "6300 Clayton Ave. (352-156)",
  "634 N. Grand Ave. TIF (352-147)",
  "7 Highway and 40 Highway Tax Increment Project A",
  "7 Highway and 40 Highway Tax Increment Project B",
  "7 Highway and 40 Highway Tax Increment Project C",
  "706 Market (352-142)",
  "721 Olive Chemical Building (352-114)",
  "811 Main Project 1 TIF Plan",
  "811 Main TIFProject 1 - Commerce Bank",
  "87th and Hillcrest Road TIF Plan",
  "920 Olive/1000 Locust (352-24)",
  "9th &amp; Central TIF Plan",
  "A.D. Brown Building (352-58)",
  "Adams Farm TIF Plan Projects A, B and C",
  "Adler Lofts-20121-2101 Washington Ave. (352-49)",
  "Affton Plaza Redevelopment Area",
  "Ambride Commons",
  "American Electric Building Redevelopment",
  "Americana TIF Plan",
  "Antioch Crossing TIF Plan",
  "Antioch Mall Quick Trip Project 10 TIF Plan",
  "Antioch Mall TIF Plan",
  "Appleton City D/T Improvment Plan",
  "Argyle Redevelopment Plan (352-07)",
  "Arlington Road TIF Plan",
  "Army Ammunition Plant (352-72)",
  "Arnold Crossroads Redevelopment Plan",
  "Arnold Triangle Redevelopment Plan",
  "Arrowhead Development Group, LLC",
  "Aurora Marketplace TIF",
  "Automobile Row (352-52)[]",
  "Automobile Row-31xx Olive, Locust, Washington",
  "Ballpark Lofts (352-84)",
  "Ballwin Town Center TIF Redevelopment Plan",
  "Baltimore Place Properties TIF Plan",
  "Baltimore Place TIF PlanProjects 1 &amp; 2",
  "Baltimore Place TIFNelkin Bldg - Project 3",
  "Bannister &amp; I-435 TIF Plan",
  "Bannister &amp; Wornall TIFPlan",
  "Barrytowne (Project 1, 3a and 4) TIF Plan",
  "Barrytowne TIF Plan",
  "Barton Street (Tabernacle Lofts) (352-44)",
  "Bee Hat Building (352-76)",
  "Bel-Ridge North Tax Increment Financing District",
  "Belton Marketplace TIF Plan",
  "Belton Town Centre TIF Plan",
  "Berkeley Lumber Company Project",
  "Bliss Land Development TIF Plan",
  "Blue Ridge Crossing East Tax Increment Financing",
  "Blue Ridge Mall TIF Plan",
  "Bluffs at Sugar Creek TIF Plan",
  "Boardwalk at Belton TIF Plan",
  "Bolger Square TIF Plan",
  "Boonslick Hwy Redevelopment Plan",
  "Bottle District (352-59)",
  "Branson Hills Redevelopment Project",
  "Branson Landing Redevelopment Project",
  "Branson Meadows TIF 1995",
  "Brentwood Pointe (Eager Rd) Projects 2 and 3",
  "Brentwood Promenade (Eager Road) Project 1",
  "Briarcliff West TIF Plan",
  "Broadway Hotel Phase Two Redevelopment Plan",
  "Brush Creek - Blue Pkwy (Project A) TIF Plan",
  "Brush Creek - Blue Pkwy (Project D) TIF Plan",
  "Brush Creek - Blue Pkwy (Projects A and D) TIF Plan",
  "Brush Creek - Blue Pkwy (Projects B and C) TIF Plan",
  "Brush Creek - Plaza East TIF Plan",
  "Brush Creek - Plaza Library TIF Plan",
  "Brush Creek-Blue Parkway (Project B &amp; C) TIF Plan",
  "Brywood Centre TIF Plan",
  "Buzz Westfall Plaza on the Blvd. TIF #3",
  "C/R-Rainen #464 SAF TIF Plan",
  "Cabool Tax Increment Financing Redevelopment",
  "Cambridge Commons",
  "Capital Mall TIF Plan",
  "Carondelet Coke (352-140)",
  "Carondelet South-District #1 (352-110a)",
  "Carondelet South-District #2 (352-110b)",
  "Carondelet South-District #3 (352-110c)",
  "Carondelet South-District #4 (352-110d)",
  "Carondelet Village Redevelopment Plan",
  "Carondolet Drive",
  "Carrie Ave. (352-141)",
  "Catlin Townhomes (352-41)",
  "CC Plaza (Project 1, Seville Square) TIF Plan",
  "CC Plaza (Project 2, Granada and Saks) TIF Plan",
  "CC Plaza (Project 3, Valencia Place) TIF",
  "CC Plaza (Project 7, Park Lane) TIF",
  "CC Plaza Kirkwood Circle TIF Plan",
  "CC Plaza/4900 Main #353 SAF TIF Plan",
  "Cedar Tree TIF Redevelopment Plan",
  "Center for Emerging Tech/Doris Wing (352-11)",
  "Central Business District TIF",
  "Chambers/West Florissant Redevelopment Project",
  "Chapel Ridge Tax Increment Financing District",
  "Chatham TIF Plan",
  "Chemical Building (352-114)",
  "Chouteau Crossing (352-118)",
  "Chouteau/Compton Industrial Center (352-6)",
  "Chouteau/I-35 Project 3 TIF Plan",
  "Chouteau/I-35 Project 4 TIF Plan",
  "Chouteau/I-35 Projects 1 and 2 TIF Plan",
  "Chouteau/Newstead (352-100)",
  "City Center At McKnight",
  "City Foundry (352-151)",
  "City Place III and IV Redevelopment Project",
  "Civic Mall-422 Admiral (Project 13) TIF Plan",
  "Civic Mall-JE Dunn (Projects 66 and 67) TIF Plan",
  "Civic Mall-Vista Del Rio TIF Plan",
  "Civic Mall-Whittake Courthouse (Project 46-47)",
  "Civic Mall-Whittaker Courthouse (Projects 46 and 47)",
  "Colton's Steakhouse and Grill",
  "Commerce Bank Village TIF",
  "Commercial Street TIF",
  "Convention Headquarters Hotel (352-03)",
  "Cook Road Corridor",
  "Copperleaf Village Shopping Center TIF Plan",
  "Cornerstone TIF Plan",
  "Country Club Plaza (Project 1, Seville Square) TIF",
  "Country Club Plaza (Project 2, Granada and Saks)",
  "Country Club Plaza (Project 3, Valencia Place) TIF",
  "Country Club Plaza (Project 7, Park Lane) TIF Plan",
  "Country Club Plaza (Project 8, 4900 Main) TIF",
  "Country Club Plaza (Project 8, Kirkwood Circle)",
  "Crackerneck Creek Tax Increment Financing Plan",
  "Crestwood Plaza",
  "Crestwood Point TIF Plan",
  "Cross Keys Redevelopment Project",
  "Crossroads Development Plan TIF",
  "Crossroads II Tax Increment Financing Plan",
  "Cupples Station (352-02)",
  "Deer Creek ",
  "Deer Creek Redevelopment Project",
  "Delmar East Loop (352-80D)",
  "Dierberg's Fenton Crossing Project",
  "Dierbergs Osage Beach Redevelopment Project",
  "Dogtown Walk II-6815-29 Waldemer Ave. (352-62)",
  "Dollar General Store ",
  "Downtown Cape Girardeau TIF- RPA #1",
  "Downtown Library District, Projects 1 and 2 TIF",
  "Downtown Park Hills Redevelopment District 4",
  "Downtown Raytown TIF",
  "Downtown Redevelopment Plan",
  "Downtown Washington Redevelopment Plan &amp; Project",
  "Dr. Martin Luther King Plaza (352-18)",
  "East Bank Lofts-1511 Washington Ave. (352-64)",
  "East Dorsett Redevelopment District",
  "East Hills Mall",
  "East U.S. Highway 50 Corridor Improvement TIF Plan",
  "East Village (Project 1) TIF Plan",
  "East Village (Projects 2 and 3) TIF Plan",
  "Eastland Center Tax Increment Financing and Redeve",
  "Eastland Center TIF Redevelopment Plan",
  "EBR Enterprises, LLC/HHS Properties Inc.",
  "Edinger Road TIF Redevelopment",
  "Edison Brothers Warehouse (352-8)",
  "Eight Points Tax Increment Financing Redev Plan",
  "Ellsinore TIF District",
  "Elm Grove (incl. Hazelwood Plaza)",
  "Elm Point Redevelopment Area Phase I &amp; II",
  "Elms Hotel TIF",
  "Ely Walker Lofts-1520 Washington Ave.(352-73)",
  "Esquire TIF",
  "Euclid/Buckingham Garage (352-81)",
  "Eureka-South I-44 Redevelopment Area 2005 TIF Plan",
  "Exit 110 TIF Plan",
  "Fall Creek Tax Increment Financing Plan",
  "Fashion Square Lofts-1301 Washington Ave. (352-37)",
  "Fast Lanes Recreational Center TIF",
  "Fenton Logistics Park Redevelopment Plan &amp; Project",
  "First Amended I-70 Interchange Plan of Higginsvill",
  "First Amended I-70 Interchange Plan Project 1",
  "First Amended I-70 Interchange Plan Project 2",
  "Flood Protection Plan Redevelopment",
  "Ford Building (352-121)",
  "Fountain Lake/West 370 Redevelopment",
  "Foxwood Village Shops Tax Increment Finance Plan",
  "Francis Place Redevelopment Project Area 2",
  "Francis Place Redevelopment Project Area 3",
  "Francis Place Redevelopment Project Areas 1 and 4",
  "Frene Creek TIF District",
  "Front Street Development, LLC",
  "Fulton Commons Redevelopment Project",
  "Fulton Public Improvement Plan",
  "Gailoyd (Projects 1, 3 and 4) TIF Plan",
  "Gailoyd (Projects 2a, 2b and 5) TIF Plan",
  "Gailoyd TIF Plan",
  "Gaslight Square East-41xx Olive St. (352-51)",
  "Gateway 2000 TIF Plan",
  "Gateway I-170",
  "Gateway Redevelopment Plan",
  "Georgian Square (352-36 RPA 2)",
  "Georgian Square (352-36 RPA 3)",
  "GEW Lofts-2601-43 Washington Ave. (352-92)",
  "Gilmore Building Redevelopment",
  "Gladstone Plaza TIF Plan",
  "Golf Course TIF",
  "Golf Strategies Tax Increment Financing Plan",
  "Good Ranch Redevelopment Area TIF Plan",
  "Grace Lofts-1324 Washington Ave. (352-28)",
  "Grain Valley Interchange TIF Project 1A",
  "Grain Valley Marketplace TIF Plan",
  "Grain Valley Marketplace TIF- Project #2",
  "Grain Valley MarketplaceInterchange TIF",
  "Granby TIF District",
  "Grand &amp; Shenandoah (352-94)",
  "Grand Boulevard TIF Plan",
  "Grand Boulevard-Watkins (Projects K-1 and L-1) TIF",
  "Grand Center (352-20)",
  "Grand Reserve TIF Plan",
  "Grandview Crossing Redev. Area (TIF Dist. #14)",
  "Grandview Crossing Redevelopment Area",
  "Grandview Crossing Redevelopment TIF 1",
  "Grandview Crossing Redevelopment TIF 2",
  "Grasso Plaza Redevelopment Area",
  "Gravois Bluffs Redevelopment Project",
  "Gravois Plaza (352-13)",
  "Hadley Dean Building (352-125)",
  "Hadley Township Redevelopment Area",
  "Hadley Township Redevelopment Project Area-North",
  "Hadley Township Redevelopment Project Area-South",
  "Hall's Ferry/I-270 Redevelopment Plan",
  "Hampton Inn @ the Highlands (352-38)",
  "Hanley Road/South of Folk Avenue Redev. Area",
  "Hanley Station--Hanley/Strassner TIF Redevelopment",
  "Harrisonville Marketplace",
  "Harrisonville Towne Center",
  "Hartley Block Tax Increment Financing Plan",
  "Hartman Heritage Center TIF Plan",
  "Hazelwood Logistics Center",
  "Hearth of the City Neighborhood TIF Plan",
  "Hickman Mills TIF Plan",
  "High Street Tax Increment Financing Plan",
  "Highway 141/Manchester Road Redevelopment Area TIF",
  "Highway 177 TIF District",
  "Highway 47/67 TIF District Development",
  "Highway 58 and Dean Avenue TIF",
  "Highway 61 Redevelopment Area TIF Plan",
  "Highway 67 Corridor Redevelopment District 2",
  "Highway 67 Tax Financing District",
  "Highway 67 Tax Increment Finance District",
  "Highway 67/72 TIF District",
  "Highway 6732 Corridor",
  "Highway H Redevelopment",
  "Hillsboro Hills Redevelopment Plan and Project",
  "Hilltop Plaza Redevelopment Area (T3)",
  "Historic Clarksville Revitalization Plan",
  "Holiday Inn Express",
  "Hollister Parkway Redevelopment TIF Project 1",
  "Horseshoe Bend Interior District TIF Plan",
  "Hotel Phillips (Project A) TIF Plan",
  "Hotel Phillips (Projects B and C) TIF Plan",
  "Hwy 136/111 TIF Plan",
  "Hwy 58 West Extended Redevelopment Plan",
  "Hy-Vee Center TIF Plan",
  "I-29/Hwy 136 TIF Plan",
  "I-385 Levee Redevelopment Plan",
  "I-44 East Redevelopment Project 1",
  "I-44/US 63 TIF Redevelopment Plan &amp; Project",
  "I-470 and 350 Highway TIF District",
  "I-470 and View High Tax Increment Financing Plan",
  "I-470 Business &amp; Technology Center Tax Increment",
  "I-55/McNutt Street Tax Increment Financing",
  "I-57 Redevelopment Area",
  "I-70 and Little Blue Parkway Tax Increment Finance",
  "I-70 Corporate Parkway",
  "Independence Regional Medical Center TIF Plan",
  "Independence Square",
  "Indian Point Road TIF District",
  "Jazz District TIF Plan",
  "Jefferson Arms (2016) (352-155)",
  "Jefferson Arms-401-15 N. Tucker (352-87)",
  "Jennings Station Crossing RPA #1 TIF Plan",
  "Jennings TIF Area #1",
  "Jordan Valley Park TIF",
  "Jordan's Keep Redevelopment Area",
  "Judicial Square TIF Plan",
  "Kansas City Convention Headquarters Hotel",
  "Karsch Downtown Redevelopment District",
  "KCI Corridor (Project 5) TIF Plan",
  "KCI Corridor (Projects 1, 2 and 4) TIF Plan",
  "KCI Corridor (Projects 6-10, 14-20) TIF Plan",
  "KCI Corridor TIF Plan",
  "KCI Corridor TIF PlanMenards",
  "Kenilworth (Brentwood Square) Redevelopment Area",
  "Keystone &amp; West View Pad Sites Tax Increment Finan",
  "Kirksville Downtown Improvement TIF Plan",
  "l-385 Levee Redevelopment Plan",
  "Laclede Power House (352-101)",
  "Lafayette Square Historic District (352-14)",
  "Lamar TIF Redevelopment Plan",
  "Lambert Airport Eastern Perimeter RPA 1",
  "Lambert Airport Eastern Perimeter RPA 2",
  "Lambert Airport Eastern Perimeter TIF",
  "Lambert Airport Eastern Perimeter TIF RPA 3",
  "Lambert Airport Eastern Perimeter TIF RPA 3(a)",
  "LaSalle Building (352-111)",
  "LCM Courtney Atherton TIF Plan",
  "Leather Trades Building-1600 Locust St. (352-99)",
  "Lemay Plaza",
  "Lemay Plaza TIF Project",
  "Liberty Commons",
  "Liberty Commons TIF Redevelopment Plan",
  "Liberty Triangle (Areas A-H) TIF Project",
  "Liberty Triangle (Blue Jay Crossing Area 1) TIF",
  "Liberty Triangle Tax Increment Financing District",
  "Liberty Triangle TIF Project",
  "Lindell Condominiums (352-79)",
  "Linwood Shopping Center TIF Plan",
  "LMP Steel and Wire Expansion TIF",
  "Loop Hotel (352-80A)",
  "Louderman Building (352-25)",
  "Loughborough Commons (352-61)",
  "Louisa Food Products TIF #2",
  "Lucas-Hunt/Chandler Redevelopment Area",
  "Ludwig Lofts-1004-06 Olive St. (352-53)",
  "M&amp;B Sachs Business Park Extension",
  "Magnolia-Thurman (352-103)",
  "Mall at Sni-A-Bar TIF Plan",
  "Manchester/Ballas Redevelopment Project",
  "Manion Plaza Redevelopment Plan",
  "Maplewood Square",
  "Marina View Redevelopment Area",
  "Market at McKnight",
  "Marketplace Shopping Center",
  "Marquette Building-413-27 Olive St. (352-57)",
  "Marquette Building-413-27 Olive St. (352-57))",
  "Maryland Plaza North (352-7p1)",
  "Maryland Plaza South (352-7p2)",
  "Maryville Town Center Redevelopment Area 1 TIF",
  "Mayfair Plaza",
  "Mayfair Plaza TIF Redevelopment Area",
  "McCormick Place TIF Project",
  "McKnight Crossing",
  "Meacham Park Redevelopment Project",
  "Meridian Project (Hanley/Eager) Redevelopment Plan",
  "Methodist Church Redevelopment TIF Plan",
  "Metro North TIF Plan",
  "Mid America Industrial Park Development",
  "Midtown Lofts (352-116)",
  "Mid-Town Truman Road Corridor Plan and Redevelopment",
  "Midtown-Linwood TIF Plan",
  "Midtown-Mill Street TIF Plan",
  "Miner Gateway Redevelopment Project",
  "Mississippi Place-1602-26 Mississippi Ave (352-56)",
  "Missouri Good Ranch Redevelopment TIF Plan",
  "Mitchell Avenue Corridor",
  "Moon Brothers Carriage Lofts (352-67)",
  "Mosaic Downtown Revitalization TIF",
  "Mound City Tax Increment Financing District",
  "Mount Washington Tax Increment Financing Plan",
  "MP-L4 Redevelopment Plan",
  "Municipal Courts Building (352-139)",
  "N. Broadway Carrie (352-130)",
  "Nadira Place (352-104)",
  "Natural Bridge Road Redevelopment Area",
  "Natural Bridge Road TIF District",
  "NE Hwy 65 &amp; Municipal DR. Phase 1&amp;2 Redevelopment",
  "Neosho Tax Increment Finance District",
  "New England Bank Building TIF Plan",
  "New Longview Tax Increment Financing Plan",
  "New Longview Tax Increment Financing Plan (2016)",
  "New York Life TIF Plan",
  "No Name Was Provided",
  "Noland Road and 23rd Street Tax Increment Finance",
  "Noland Road Auto Plaza TIF Plan",
  "North Broadway/Carrie",
  "North County Development - Project #1",
  "North Economic Development Area",
  "North Highway 21 Redevelopment Area",
  "North Independence Redevelopment TIF Plan",
  "North Kansas City Destination Developers TIF Plan",
  "North Main &amp; Malone Development Area",
  "North Oak (Project 1) TIF Plan",
  "North Oak (Projects 3, 4, 5a, 5b and 6) TIF Plan",
  "North Oak Trafficway TIF Plan",
  "North Oak-Cerner (Project 1) TIF Plan",
  "North Park Crossing TIF Plan",
  "Northeast Hampton/Berthold (32-138)",
  "Northeast HamptonI-44 Ackerman Toyota (352-146)",
  "Northeast TIF District",
  "Northgate (352-153)",
  "Northgate Village Tax Increment Financing Plan",
  "Northland Development Redevelopment Area TIF",
  "Northside Regeneration (352-126)",
  "Northwest Economic Development Area",
  "Northwest Interstate TIF Plan",
  "Northwest Plaza Redevelopment Project",
  "Oak Ridge Redevelopment Area",
  "Old Landfill TIF Plan and Redevelopment Project",
  "Old Post Office Building (352-15)",
  "Old Town Redevelopment Area TIF",
  "Olive Central TIF",
  "Olive East TIF",
  "Osage National Project TIF Plan #1",
  "Osage National Retail District",
  "Packard Lofts-2221 Locust St. (352-74)",
  "Page Avenue/I-270 Redevelopment Area",
  "Page Partners III/Walgreens (352-89)",
  "Pagedale TIF Redevelopment Plan",
  "Paradise Playhouse TIF",
  "Park 370 Redevelopment Project",
  "Park Pacific (352-90)",
  "Parkville Commons",
  "Parkway Drive Redevelopment District 3",
  "Parvin Road TIF Plan",
  "Paul Brown/Arcade Building (352-26)",
  "Peach Tree Plaza Redevelopment Plan and Project",
  "Peerless Park Redevelopment Project",
  "Performing Arts (Projects 1 and 2) TIF Plan",
  "Performing Arts (Projects 3 and 4) TIF Plan",
  "Pershing Road (IRS Service Center) TIF Plan",
  "Pet Building-400 S. 4th St. (352-65)",
  "Pioneer Place",
  "Platte Purchase TIF Plan",
  "Plaza at Noah's Ark",
  "Prewitt's Highway 54 Enterprises LLC",
  "Price Chopper TIF",
  "Printer's Lofts-1601-27 Locust St. (352-32)",
  "Prospect North TIF Plan",
  "Railway Exchange Building (352-128)",
  "Railway Lofts-1619 Washington Ave. (352-39)",
  "Ramada Inn Redevelopment Project",
  "Raytown Live Project 2",
  "Raytown Live TIF Plan",
  "Recovery Sales Outlet Tax Increment Financing Plan",
  "Recovery TIF",
  "Redevelopment Plan for downtown Perryville Tax",
  "Redevelopment plan for the Downtown Ste. Genevieve",
  "Redevelopment Plan for the Downtown TIF District",
  "Redevelopment Plan for the Highway 51/61 Tax",
  "Redevelopment Plan for the Hwy 67/72 Tax Increment",
  "Redevelopment Plan for the I-55/Perryville Blvd.",
  "Redevelopment Plan for the Ozora Area TIF",
  "Redevelopment Project Area No. 8 TIF Plan",
  "Regency Hotel Redevelopment Plan and Project TIF",
  "REO (352-117)",
  "Rhine River Redevelopment Plan &amp; Project",
  "RIS Incorporated The Shoppes at Eagle's Landing",
  "Ritter Plaza Tax Increment Financing Plan",
  "River Market #500 SAF TIF Plan",
  "River Market (Project 11) TIF Plan",
  "River Market (Project 16) TIF Plan",
  "River Market (Project 17, Republic Paper) TIF Plan",
  "River Market TIFProject 16 - 4th &amp; Locust Bldg",
  "River Roads Estates Redev. Project Area 7B TIF",
  "River Roads Plaza Project Area 7A TIF Plan",
  "Riverbend TIF",
  "Riverfront (Projects 1, 10, 12 and 15) TIF Plan",
  "Rogers Plaza TIF District",
  "Rt 141 / Marshall Road Redevelopment Plan",
  "Ryan's Block - Uptown Redevelopment Project B",
  "S. U.S. Hwy 160 Corridor/Porter Wagoner Bl. R.P.",
  "S. U.S. Hwy. 60 Corridor/Porter Wagoner Bl. R.P.",
  "Sam's Wholesale Club",
  "Santa Fe TIF Plan",
  "Santa Fe Trail Neighborhood TIF",
  "Sarcoxie TIF District",
  "Savoy Hotel TIF Plan",
  "Scott County I-55 Redevelopment Project",
  "Scullin Redevelopment/St. Louis Marketplace (352-1)",
  "Searcy Creek TIF Plan",
  "Security Building (352-40)",
  "Sedalia Midtown TIF Redevelopment Plan &amp; Project",
  "Shamrock Cabinet TIF",
  "Shelbina Redevelopment Area TIF",
  "Shenandoah Place-2303-11 Minnesota Ave. (352-42)",
  "Shoal Creek (Hunt Midwest) TIF Plan",
  "Shoppes at Kearney",
  "Shoppes at North Gate Redevelopment Plan",
  "Shoppes at Old Webster TIF Plan",
  "Simon Square",
  "Sky Wheel (352-119)",
  "Smithville Commons TIF Redevelopment Plan",
  "Smithville Commons TIF Redevelopment Plan (2017)",
  "Solar Woods / Solar Stone Redevelopment TIF",
  "Soulard Market Apartments-1535 S. 8th St. (352-34)",
  "South 70 Commercial Area - East",
  "South 70 Commercial Area-East",
  "South Big Bend TIF Redevelopment Project",
  "South Heights Redevelopment Area TIF",
  "South Highway 63 TIF Plan",
  "South U.S. Highway 160 TIF Plan",
  "South US 65 TIF Plan",
  "Southside National Bank (352-75)",
  "Southside Tax Increment Financing Plan",
  "Southtown (352-31)",
  "Southtown Corridor31st &amp; Baltimore TIFProject H",
  "Southtown Urban Life Development TIF Plan",
  "Southtown/31st and Baltimore (Project G) TIF Plan",
  "Southtown/31st and Baltimore (Project I) TIF Plan",
  "Southtown/31st and Baltimore TIF Plan",
  "Southtowne Plaza TIF Plan",
  "Southwest Economic Development Area",
  "Springfield Plaza TIF",
  "St. Charles Center/Mark Twain Mall",
  "St. Charles County Convention Center Redevelopment",
  "St. Charles Rock Road Redevelopment Project (T4)",
  "St. Cyr Road Redevelopment Project",
  "St. John Crossing TIF",
  "St. John Crossings (TIF District #1)",
  "St. John Crossings (TIF District #2)",
  "St. John TIF District Projects 1 - 7",
  "St. Louis Centre (352-88)",
  "St. Marys Hospital TIF Plan",
  "St. Peters Centre Redevelopment Area TIF",
  "St. Peters Route 370 TIF Development Plan",
  "St. Robert Redevelopment Project #2",
  "St.Louis Innovation District (352-137)",
  "Stardust Munger Diamond Redevelopment Project",
  "Station G Apartments (352-106)",
  "Sterling Village TIF Plan and Redevelopment District",
  "Stockyards Redevelopment",
  "Strafford TIF District",
  "Streets of West Pryor Tax Increment Financing Plan",
  "Sugarland Center TIF Redevelopment Plan",
  "Summit Fair Tax Increment Financing Plan",
  "Summit TIF PlanProject 25",
  "Summit-Output Technologies TIF Plan",
  "Summit-Output Technologies TIFProj 1, 2, 21, &amp; 26",
  "Summit-Pershing Building (Project 8) TIF Plan",
  "Sunrise Beach Market Center Tax Increment",
  "Sunrise Farms Redevelopment Area",
  "SW Clarkson and Manchester Redevelopment Area",
  "Switzer Building (352-69)",
  "Syndicate Trust Building-915 Olive St. (352-77)",
  "Taylor Carrie (352-123)",
  "Tech Electronics (352-17)",
  "Terra Cotta Annex and Garage (352-29)",
  "The Armory District (352-154)",
  "The Briscoe's Ozark Development Group TIF Plan",
  "The Center Building",
  "The Cloisters-2500 S. 18th St. (352-35)",
  "The Foundry (352-95)",
  "The Georgian at City Hospital (352-36)",
  "The Interstate 55 Corridor Redevelopment Project",
  "The Kenrick Plaza Redevelopment Project",
  "The Laclede Power House (352-101)",
  "The Laurel/555 Washington (352-109)",
  "The Loop Center North (352-80B)",
  "The Pet Building (352-65)",
  "The Tuscany Towers",
  "The Union Club (352-83)",
  "Third Street Hotel Development",
  "Three Trails TIF Plan",
  "TIF #10-Botts Road Industrial Redevelopment Area",
  "TIF #12-Patel Redevelopment Area",
  "TIF #13-Grandview Crossing Redevelopment Area",
  "TIF #14-Sunrise Farms Redevelopment Area",
  "TIF #15-Truman's Landing Redevelopment Area",
  "TIF #8- Downtown Grandview",
  "TIF #9-Gateway Commons Redevelopment Area",
  "TIF 1 Redevelopment Area",
  "TIF 2 Redevelopment Area",
  "Tiger Hotel Redevelopment TIF",
  "Tower Properties (Project A) TIF Plan",
  "Tower Properties (Project B) TIF Plan",
  "Tower Properties (Project H) TIF Plan",
  "Trenton AMS Mall TIF Project",
  "Trinity TIF Plan and Redevelopment Project",
  "Truman Corners Shopping Center Revitalization",
  "TSG Osage Beach, LLC",
  "Tudor Building/1818 Washington (352-91)",
  "Union Hill TIF Plan",
  "Union Hill-KCPT (Projects C1, 2, 3 and D) TIF Plan",
  "Union Station Phase 2 (352-145)",
  "Unionville TIF Plan",
  "Unity Village TIF Redevelopment Plan",
  "Universal Floodwater TIF Plan",
  "Upper Gateway Mixed-Use Redevelopment Plan",
  "Uptown St Joseph",
  "Uptown Theater TIF Plan",
  "US 65 and Birch TIF Plan",
  "US Highway 54 and Business Hwy 54 TIF Plan",
  "US Highway 63 Bypass",
  "USA 800 Redevelopment Plan",
  "Valle Springs TIF District",
  "Valley Park Levee and Infrastructure Project",
  "Ventana Lofts-1635 Washington Ave. (352-68)",
  "Venture Industrial Park",
  "Village at View High Tax Increment Financing Plan",
  "Vintage Plaza II TIF",
  "Vintage Plaza TIF",
  "Vivion Point TIF Plan",
  "W 17th Street TIF Plan",
  "Wal-Mart/Elms TIF",
  "Walnut Creek TIF Plan",
  "Walter Knoll Florist Row (352-27)",
  "Warehouse of Fixtures (352-50)",
  "Warrenton West Development TIF RPA1",
  "Washington East Condominiums (352-54)",
  "Watson Plaza TIF Plan",
  "Wayland Hwy 27 TIF Plan",
  "Wellston Heights Redevelopment Area",
  "West 17th Street TIFProject C - Vitagraph Bldg",
  "West 370 Redevelopment Area",
  "West Blue Ridge Development Project",
  "West Clay Extension",
  "West Edge (Projects 1 and 2) TIF Plan",
  "West Interstate Area Addition-South District",
  "West Old U.S. Hwy 71 Access Road Area",
  "West Platte Road Redevelopment Plan",
  "West Town Lofts (352-71)",
  "Westport Plaza Redevelopment ",
  "Westside Marketplace Redevelopment Project",
  "White Oak TIF",
  "Whitehall Station TIF District Redevelopment Plan",
  "Willy's Overland Building- 2300 Locust St (352-66)",
  "Wilson Creek MarketPlace",
  "Winchester Ventures TIF Plan",
  "Winchester-KMBC (Project 3) TIF Plan",
  "Winchester-Visions (Project 13) TIF Plan",
  "Windows Lofts-1601 Washington Ave. (352-33)",
  "Woodland Hills Redevelopment Project",
  "Woods Chapel TIF Plan Project 1",
  "Woods Chapel TIF Plan Project 2",
  "Woods Chapel TIF Plan Project 3",
  "Woodson Village Shopping Center Redevelopment Area",
  "Y - Belton Plaza TIF Plan",
  "Y Highway Market Place TIF Pla")


tif_ids

tif_get_init <- function(project_name) {
  # url
  url <- "https://app.auditor.mo.gov/TIF/SearchTIF.aspx"
  
  # create session
  session <- rvest::html_session(url)
  
  # construct form
  form <- rvest::html_form(session)[[1]]
  
  filled.form <- form
  
  filled.form <- rvest::set_values(filled.form, 'ctl00$ContentPlaceHolder1$ddlProjectName' = project_name)
  filled.form$url <- ""
  
  # Submit form
  session <- rvest::submit_form(session = session, form = filled.form)
  
  # return output
  tif_get_table(session, project_name)
}

tif_get_table <- function(session, project_name) {
  # update session to correct page
  # if (page > 1){
  #  session <- tif_switch_page(url = url, session = session, form = form, page = page)
  # }
  
  # scrape table for Mo Auditor Database TIF IDs
  these_tif_ids <- rvest::html_nodes(session, "table tr td a") %>%
    rvest::html_attr("href") %>%
    stringr::str_match("vTIF\\.aspx\\?id\\=([0-9]{1,})+") %>%
    na.omit()
  these_tif_ids <- these_tif_ids[,-1]
  # typeof(these_tif_ids)
  tif_ids <- append(these_tif_ids, tif_ids)
}



#' Download TIF IDs List from the Missouri Auditor's Office
#'
#' @description Downloads TIF reporting data from the Missouri Auditor's website
#'
#' @usage tif_get_data(locale)
#'
#' @param locale The locale (county) to get data for
#'
#' @return An ID list for all time.
#'
#' @export
tif_get_data <- function() { #locale, year
  lapply(tif_project_names, function(x) tif_get_init(x))
}


tif_get_data()
